In [1]:
import numpy as np


In [2]:
np

<module 'numpy' from 'C:\\Users\\Wechuli\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
np.array(1,2,3)

ValueError: only 2 non-keyword arguments accepted

In [5]:
np.array([12,4,4])

array([12,  4,  4])

In [7]:
np.array([2,3],[3,4])

TypeError: data type not understood

In [8]:
my_list = [-1,0,1]

In [9]:
type(my_list)

list

In [11]:
myarray=np.array(my_list)

In [12]:
myarray,type(myarray)

(array([-1,  0,  1]), numpy.ndarray)

In [13]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
myndarray = np.array(my_matrix)

In [15]:
myndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
my_tuple = (-1,0,-1)

In [17]:
my_tarray = np.array(my_tuple)

In [18]:
type(my_tarray),my_tarray

(numpy.ndarray, array([-1,  0, -1]))

In [19]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,1001,0.2)

array([0.0000e+00, 2.0000e-01, 4.0000e-01, ..., 1.0004e+03, 1.0006e+03,
       1.0008e+03])

In [21]:
np.sum

<function numpy.core.fromnumeric.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>)>

In [22]:
np.sum(np.arange(0,1000,0.2))

2499500.0

In [23]:
np.arange(0,1000,0.2,dtype=float)

array([0.000e+00, 2.000e-01, 4.000e-01, ..., 9.994e+02, 9.996e+02,
       9.998e+02])

In [28]:
#Return evenely spaced points
np.linspace(1,16,50,dtype=float)

array([ 1.        ,  1.30612245,  1.6122449 ,  1.91836735,  2.2244898 ,
        2.53061224,  2.83673469,  3.14285714,  3.44897959,  3.75510204,
        4.06122449,  4.36734694,  4.67346939,  4.97959184,  5.28571429,
        5.59183673,  5.89795918,  6.20408163,  6.51020408,  6.81632653,
        7.12244898,  7.42857143,  7.73469388,  8.04081633,  8.34693878,
        8.65306122,  8.95918367,  9.26530612,  9.57142857,  9.87755102,
       10.18367347, 10.48979592, 10.79591837, 11.10204082, 11.40816327,
       11.71428571, 12.02040816, 12.32653061, 12.63265306, 12.93877551,
       13.24489796, 13.55102041, 13.85714286, 14.16326531, 14.46938776,
       14.7755102 , 15.08163265, 15.3877551 , 15.69387755, 16.        ])

In [30]:
np.linspace(1,15,31,retstep=True)

(array([ 1.        ,  1.46666667,  1.93333333,  2.4       ,  2.86666667,
         3.33333333,  3.8       ,  4.26666667,  4.73333333,  5.2       ,
         5.66666667,  6.13333333,  6.6       ,  7.06666667,  7.53333333,
         8.        ,  8.46666667,  8.93333333,  9.4       ,  9.86666667,
        10.33333333, 10.8       , 11.26666667, 11.73333333, 12.2       ,
        12.66666667, 13.13333333, 13.6       , 14.06666667, 14.53333333,
        15.        ]), 0.4666666666666667)

In [31]:
#create an array ith zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
#pass in a tuple to the np and this returns an n,d array with zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
#we can get ones instead
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [34]:
#we can create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
#we can create random numbers with numpy
np.random

<module 'numpy.random' from 'C:\\Users\\Wechuli\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [37]:
np.random.rand(6)

array([0.63824135, 0.16080551, 0.5138539 , 0.09875197, 0.66075436,
       0.88005407])

In [39]:
#we can create nd array with random values
np.random.rand(4,5)

array([[0.9956478 , 0.55944739, 0.90143293, 0.04302382, 0.62769412],
       [0.81879786, 0.24702796, 0.91749215, 0.63669012, 0.48847124],
       [0.71260542, 0.70611933, 0.44638457, 0.20364706, 0.16024092],
       [0.55472369, 0.29917861, 0.0133367 , 0.96093903, 0.25667929]])

In [40]:
#to get the gaussian distribution random use randn
np.random.randn(15,4)

array([[ 0.71494627,  1.11008387, -0.46355224,  1.44364832],
       [ 1.75590567,  0.11316299, -1.21868287, -0.87240988],
       [ 0.45191383, -1.25873051,  1.06384027,  0.54905015],
       [ 0.62096065, -0.63228148, -0.64609708,  1.37939972],
       [-1.82521607,  1.29721906, -1.0601125 , -0.99133549],
       [-1.99153001,  0.21799096, -0.53095075,  0.32761432],
       [-0.35327565, -0.42762265, -0.59945482,  1.18619704],
       [ 0.15225853, -1.89244579, -0.4384828 ,  0.70405874],
       [-2.29506375,  2.1215736 ,  2.00003554,  0.02106272],
       [ 0.48204917,  0.12010022,  0.78085574, -1.2232101 ],
       [-0.70798609,  2.18741389,  1.36035486, -0.4670371 ],
       [ 1.09054817, -1.34571822, -0.38824729,  0.10330001],
       [ 1.12373756, -0.80717724,  0.82819945, -0.25685571],
       [-0.48229122, -2.14248499,  1.05986876, -2.34704527],
       [-0.79724997, -0.17298448,  0.40964044, -0.46800829]])

In [48]:
#randint generates an integrer btw two integers
np.random.randint(2,400)

149

In [49]:
#we can return several numbers
np.random.randint(2,400,4)

array([ 50, 301, 144, 288])

In [50]:
#we can generate a matrisx of random numbers
np.random.randint(2,100,(3,4))

array([[56, 13, 32, 30],
       [ 4, 67,  5, 50],
       [73, 59, 89, 48]])

Some Numpy Mathods

In [51]:
array_arange = np.arange(16)

In [52]:
array_ranit = np.random.randint(0,100,10)

In [53]:
array_arange


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
array_ranit

array([70, 23, 28, 46, 74, 58, 24, 49, 44, 68])

In [68]:
array_arange.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [59]:
array_arange.max()

15

In [62]:
array_arange.reshape(4,4).max(axis=1)

array([ 3,  7, 11, 15])

In [63]:
array_ranit.min()

23

In [64]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [69]:
newarray = array_arange.reshape(8,2)

In [72]:
newarray.min(),newarray.argmax()

(0, 15)

In [73]:
mytest =([[3,4],[1,2],[7,2]])

In [74]:
mytest

[[3, 4], [1, 2], [7, 2]]

In [75]:
mytest = np.array(mytest)

In [76]:
mytest

array([[3, 4],
       [1, 2],
       [7, 2]])

In [81]:
mytest.argmax()

4

In [80]:
mytest.shape

(3, 2)

In [82]:
mytest.size


6

In [84]:
mytest.dtype

dtype('int32')